# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

ingress:
  ingressClassName: "nginx"
  host: "guardian.example.test"
  tls:
    secretName: "guardian-tls"

authorizationApi:
  config:
    home: "/guardian_service_dir"
    guardianAuthzCorsAllowedOrigins: "*"
    guardianAuthzAdapterSettingsPort: "env"
    guardianAuthzAdapterAppPersistencePort: "udm_data"
    guardianAuthzAdapterPolicyPort: "opa"
    guardianAuthzAdapterAuthenticationPort: "fast_api_oauth"
    isUniventionAppCenter: 0
    udmDataAdapterUrl: "http://udm-rest-api/univention/udm"
    opaAdapterUrl: "http://guardian-authorization-opa:8181/"
    oauthAdapterWellKnownUrl: "http://keycloak/realms/souvap/.well-known/openid-configuration"
    guardianAuthzLoggingLevel: "DEBUG"
    guardianAuthzLoggingStructured: "0"
    guardianAuthzLoggingFormat: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS ZZ}</green> | <level>{level}</level> | <level>{message}</level> | {extra}"
  udm:
    auth:
      username: "cn=admin"
      password: "stub_password"
      existingSecret:
        name: "guardian-udm-secret"
        keyMapping:
          password: "udmDataAdapterPassword"
  # We need to set the registry to null here to override the default value in values.yaml
  # to make unit tests pass which expect null. Since the guardian-images don't exist in the
  # global registry like other charts, we have to go this workaround.
  image:
    registry: null

managementApi:
  config:
    home: "/guardian_service_dir"
    requestsCaBundle: "/etc/ssl/certs/ca-certificates.crt"
    sslCertFile: "/etc/ssl/certs/ca-certificates.crt"
    guardianManagementCorsAllowedOrigins: "*"
    guardianManagementAdapterSettingsPort: "env"
    guardianManagementAdapterAppPersistencePort: "sql"
    guardianManagementAdapterConditionPersistencePort: "sql"
    guardianManagementAdapterContextPersistencePort: "sql"
    guardianManagementAdapterNamespacePersistencePort: "sql"
    guardianManagementAdapterPermissionPersistencePort: "sql"
    guardianManagementAdapterRolePersistencePort: "sql"
    guardianManagementAdapterCapabilityPersistencePort: "sql"
    guardianManagementAdapterAuthenticationPort: "fast_api_oauth"
    guardianManagementAdapterAuthorizationApiUrl: "http://guardian-management-api/guardian/authorization"
    guardianManagementAdapterResourceAuthorizationPort: "guardian"
    isUniventionAppCenter: 0
    sqlPersistenceAdapterDialect: "postgresql"
    sqlPersistenceAdapterDbName: "/guardian_service_dir/database/management.db"
    oauthAdapterWellKnownUrl: "http://keycloak/realms/souvap/.well-known/openid-configuration"
    guardianManagementLoggingLevel: "DEBUG"
    guardianManagementLoggingStructured: "0"
    guardianManagementLoggingFormat: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS ZZ}</green> | <level>{level}</level> | <level>{message}</level> | {extra}"
    guardianManagementBaseUrl: "http://guardian-management"
  # oauth:
  #   auth:
  #     clientSecret: "stub_secret"
  #     existingSecret:
  #       name: "stub"
  # We need to set the registry to null here to override the default value in values.yaml
  # to make unit tests pass which expect null. Since the guardian-images don't exist in the
  # global registry like other charts, we have to go this workaround.
  image:
    registry: null

managementUi:
  config:
    viteManagementUiAdapterAuthenticationPort: "keycloak"
    viteManagementUiAdapterDataPort: "api"
    viteApiDataAdapterUri: "http://localhost:8000/guardian/management"
    viteKeycloakAuthenticationAdapterSsoUri: "http://localhost:8097"
    viteKeycloakAuthenticationAdapterRealm: "ucs"
    viteKeycloakAuthenticationAdapterClientId: "guardian-ui"
  # We need to set the registry to null here to override the default value in values.yaml
  # to make unit tests pass which expect null. Since the guardian-images don't exist in the
  # global registry like other charts, we have to go this workaround.
  image:
    registry: null

openPolicyAgent:
  config:
    isUniventionAppCenter: 0
    opaDataBundle: "bundles/GuardianDataBundle.tar.gz"
    opaPolicyBundle: "bundles/GuardianPolicyBundle.tar.gz"
    opaPollingMinDelay: 10
    opaPollingMaxDelay: 15
    opaGuardianManagementUrl: "http://guardian-management-api/guardian/management"
  # We need to set the registry to null here to override the default value in values.yaml
  # to make unit tests pass which expect null. Since the guardian-images don't exist in the
  # global registry like other charts, we have to go this workaround.
  image:
    registry: null

provisioning:
  config:
    nubusBaseUrl: "https://portal.example.test"
  keycloak:
    url: "http://keycloak:8080"
    fqdn: "id.example.test"
    realm: "nubus"
    admin: "kcadmin"
    auth:
      username: "stub_username"
      existingSecret:
        name: "guardian-provisioning-secret"
    connection:
      baseUrl: "keycloak"
      host: "keycloak"
      port: 123

postgresql:
  # -- Connection parameters. These are required if you use an external database.
  connection:
    host: "postgresql"
    port: "1234"
  auth:
    username: "postgres"
    database: "postgres"
    existingSecret:
      name: "postgresql-secret"

extraSecrets:
  - name: "guardian-udm-secret"
    stringData:
      udmDataAdapterPassword: "password"

  - name: "guardian-provisioning-secret"
    stringData:
      password: "stub_password"

  - name: "postgresql-secret"
    stringData:
      password: "password"

...
