# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

ingress:
  ingressClassName: "nginx"
  host: "guardian.example.test"
  tls:
    secretName: "guardian-tls"

authorizationApi:
  config:
    home: "/guardian_service_dir"
    guardianAuthzCorsAllowedOrigins: "*"
    guardianAuthzAdapterSettingsPort: "env"
    guardianAuthzAdapterAppPersistencePort: "udm_data"
    guardianAuthzAdapterPolicyPort: "opa"
    guardianAuthzAdapterAuthenticationPort: "fast_api_oauth"
    isUniventionAppCenter: 0
    udmDataAdapterUrl: "http://udm-rest-api/univention/udm"
    udmDataAdapterUsername: "admin"
    udmDataAdapterPassword: "stub_password"
    opaAdapterUrl: "http://guardian-authorization-opa:8181/"
    oauthAdapterWellKnownUrl: "http://keycloak/realms/souvap/.well-known/openid-configuration"
    guardianAuthzLoggingLevel: "DEBUG"
    guardianAuthzLoggingStructured: "0"
    guardianAuthzLoggingFormat: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS ZZ}</green> | <level>{level}</level> | <level>{message}</level> | {extra}"
    secretRef: "guardian-udm-secret"

managementApi:
  config:
    home: "/guardian_service_dir"
    requestsCaBundle: "/etc/ssl/certs/ca-certificates.crt"
    sslCertFile: "/etc/ssl/certs/ca-certificates.crt"
    guardianManagementCorsAllowedOrigins: "*"
    guardianManagementAdapterSettingsPort: "env"
    guardianManagementAdapterAppPersistencePort: "sql"
    guardianManagementAdapterConditionPersistencePort: "sql"
    guardianManagementAdapterContextPersistencePort: "sql"
    guardianManagementAdapterNamespacePersistencePort: "sql"
    guardianManagementAdapterPermissionPersistencePort: "sql"
    guardianManagementAdapterRolePersistencePort: "sql"
    guardianManagementAdapterCapabilityPersistencePort: "sql"
    guardianManagementAdapterAuthenticationPort: "fast_api_oauth"
    guardianManagementAdapterAuthorizationApiUrl: "http://guardian-management-api/guardian/authorization"
    guardianManagementAdapterResourceAuthorizationPort: "guardian"
    isUniventionAppCenter: 0
    sqlPersistenceAdapterDialect: "postgresql"
    sqlPersistenceAdapterDbName: "/guardian_service_dir/database/management.db"
    oauthAdapterWellKnownUrl: "http://keycloak/realms/souvap/.well-known/openid-configuration"
    oauthAdapterM2mSecret: "stub_secret"
    guardianManagementLoggingLevel: "DEBUG"
    guardianManagementLoggingStructured: "0"
    guardianManagementLoggingFormat: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS ZZ}</green> | <level>{level}</level> | <level>{message}</level> | {extra}"
    guardianManagementBaseUrl: "http://guardian-management"
    secretRef: "guardian-keycloak-client-secret"

managementUi:
  config:
    viteManagementUiAdapterAuthenticationPort: "keycloak"
    viteManagementUiAdapterDataPort: "api"
    viteApiDataAdapterUri: "http://localhost:8000/guardian/management"
    viteKeycloakAuthenticationAdapterSsoUri: "http://localhost:8097"
    viteKeycloakAuthenticationAdapterRealm: "ucs"
    viteKeycloakAuthenticationAdapterClientId: "guardian-ui"

openPolicyAgent:
  config:
    isUniventionAppCenter: 0
    opaDataBundle: "bundles/GuardianDataBundle.tar.gz"
    opaPolicyBundle: "bundles/GuardianPolicyBundle.tar.gz"
    opaPollingMinDelay: 10
    opaPollingMaxDelay: 15
    opaGuardianManagementUrl: "http://guardian-management-api/guardian/management"

provisioning:
  config:
    nubusBaseUrl: "https://portal.example.test"
    keycloak:
      url: "http://keycloak:8080"
      fqdn: "id.example.test"
      realm: "nubus"
      admin: "kcadmin"
      password: "stub_password"
      credentialSecret:
        key: "adminPassword"
    managementApi:
      clientSecret: "stub_secret"
      credentialSecret:
        key: "managementApiClientSecret"


postgresql:
  # -- Set to `true` if you want PostgreSQL to be installed as well.
  bundled: true
  # -- Connection parameters. These are required if you use an external database.
  connection:
    host:
    port:
  auth:
    username: "postgres"
    database: "postgres"
    password: "postgres"
    postgresPassword: "postgres"

extraSecrets:
  - name: "guardian-keycloak-client-secret"
    stringData:
      oauthAdapterM2mSecret: "stub_client_secret"

  - name: "guardian-udm-secret"
    stringData:
      udmDataAdapterUsername: "cn=admin"
      udmDataAdapterPassword: "password"

  - name: "guardian-provisioning-secret"
    stringData:
      adminPassword: "stub_password"
      managementApiClientSecret: "stub_client_secret"

...
