# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ printf "%s-init-management-ui" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.managementUi.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.managementUi.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.managementUi.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.managementUi.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}

data:
  10-generate_config.sh: |
    #!/bin/bash

    env_variable_names=$(compgen -e)
    config='{}'

    for variable_name in $env_variable_names; do
        if [[ "$variable_name" == VITE__* ]]; then
            config=$(echo "$config" | jq --arg value "${!variable_name}" ".$variable_name = \$value")
        fi
    done
    echo "$config" > /app/config.json
...
