# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ printf "%s-open-policy-agent" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}

data:
  IS_UNIVENTION_APPCENTER: "{{ .Values.openPolicyAgent.config.isUniventionAppCenter }}"
  OPA_DATA_BUNDLE: "{{ .Values.openPolicyAgent.config.opaDataBundle }}"
  OPA_POLICY_BUNDLE: "{{ .Values.openPolicyAgent.config.opaPolicyBundle }}"
  OPA_POLLING_MIN_DELAY: "{{ include "guardian.openPolicyAgent.config.opaPollingMinDelay" . }}"
  OPA_POLLING_MAX_DELAY: "{{ include "guardian.openPolicyAgent.config.opaPollingMaxDelay" . }}"
  OPA_GUARDIAN_MANAGEMENT_URL: "{{ include "guardian.openPolicyAgent.config.opaGuardianManagementUrl" . }}"
...
