# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

{{- if .Values.provisioning.enabled }}
---
apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ printf "%s-provisioning-init" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}

data:
  KEYCLOAK_URL: {{ include "guardian.provisioning.keycloak.url" . | quote }}
...
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-provisioning-env" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
data:
  DEBUG: {{ .Values.provisioning.config.debug.enabled | quote }}
  DOMAIN: {{ .Values.global.domain | quote }}
  KEYCLOAK_USERNAME: {{ tpl .Values.provisioning.keycloak.auth.username . | quote }}
  KEYCLOAK_HOST: {{ include "guardian.provisioning.keycloak.connection.host" . | quote }}
  KEYCLOAK_REALM: {{ include "guardian.provisioning.keycloak.realm" . | quote }}
  KEYCLOAK_URL: {{ include "guardian.provisioning.keycloak.connection.baseUrl" . | quote }}
  UNIVENTION_KEYCLOAK_BOOTSTRAP_TEMP_DIR: "/tmp"
  UNIVENTION_KEYCLOAK_BOOTSTRAP_DEBUG_PAUSE_BEFORE_SCRIPT_START: {{ .Values.provisioning.config.debug.pauseBeforeScriptStart  | quote }}
  KEYCLOAK_APP_BASE_URL: {{ include "guardian.provisioning.config.nubusBaseUrl" . | quote }}
...
{{- end }}
