# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ printf "%s-nginx-conf" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.managementUi.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.managementUi.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.managementUi.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.managementUi.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}

data:
  nginx.conf: |
    server {
     listen 8080;
     {{- if not .Values.managementUi.config.nginx.disableIPv6 }}
     listen [::]:8080;
     {{- end }}
     server_name management-ui;
     root /app;
     location /univention/guardian/management-ui {
       alias /app/;
       try_files $uri /index.html;
     }

     location /univention/guardian/management-ui/favicon.ico {
       alias /app/favicon.ico;
       try_files $uri =404;
     }
     location /univention/guardian/management-ui/config.json {
       alias /app/config/config.json;
       try_files $uri =404;
     }

     location /univention/guardian/management-ui/assets/ {
       alias /app/assets/;
       try_files $uri =404;
     }
    }
...
