# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH


---

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ printf "%s-management-ui" (include "common.names.fullname" .) }}
  labels:
    {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
    {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-management-ui" (include "common.names.fullname" .)) }}
    {{- $mergedLabels := merge $uiLabels $commonLabels}}
    {{- toYaml $mergedLabels | nindent 4 }}
spec:
  replicas: {{ .Values.managementUi.replicaCount }}
  selector:
    matchLabels:
      {{- $commonLabels := include "common.labels.matchLabels" . | fromYaml }}
      {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-management-ui" (include "common.names.fullname" .)) }}
      {{- merge $uiLabels $commonLabels | toYaml | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-management-ui.yaml") . | sha256sum }}
        {{- with .Values.managementUi.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
        {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-management-ui" (include "common.names.fullname" .)) }}
        {{- $mergedLabels := merge $uiLabels $commonLabels}}
        {{- toYaml $mergedLabels | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.fullname" . }}
      {{- end }}
      {{- with .Values.managementUi.affinity }}
      affinity:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.managementUi.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.managementUi.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.managementUi.podSecurityContext }}
      securityContext:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- if .Values.managementUi.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.managementUi.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}
      initContainers:
        - name: "app-configuration"
          securityContext:
            {{- toYaml .Values.managementUi.securityContext | nindent 12 }}
          image: "{{ coalesce .Values.managementUi.image.registry .Values.global.imageRegistry }}/{{ .Values.managementUi.image.repository }}{{ if .Values.managementUi.image.sha256 }}@sha256:{{ .Values.managementUi.image.sha256 }}{{ else }}:{{ .Values.managementUi.image.tag }}{{ end }}"
          imagePullPolicy: {{ coalesce .Values.managementUi.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
          env:
            - name: "SKIP_CONFIG_GENERATION"
              value: "TRUE"
          envFrom:
            - configMapRef:
                name: {{ printf "%s-management-ui" (include "common.names.fullname" .) }}
          command:
            - sh
            - -c
            - '/entrypoint.sh; cp -a /app/* /target/app/'
          volumeMounts:
            # NOTE: using target approach
            - name: "app-config"
              mountPath: "/target/app"
      containers:
        - name: "management-ui"
          securityContext:
            {{- toYaml .Values.managementUi.securityContext | nindent 12 }}
          image: "{{ coalesce .Values.managementUi.image.registry .Values.global.imageRegistry }}/{{ .Values.managementUi.image.repository }}{{ if .Values.managementUi.image.sha256 }}@sha256:{{ .Values.managementUi.image.sha256 }}{{ else }}:{{ .Values.managementUi.image.tag }}{{ end }}"
          imagePullPolicy: {{ coalesce .Values.managementUi.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-management-ui" (include "common.names.fullname" .) }}
          volumeMounts:
            - name: "app-config"
              mountPath: "/app"
            - name: "nginx-conf"
              mountPath: "/etc/nginx/sites-enabled/default"
              subPath: "nginx.conf"
            - name: "var-lib"
              mountPath: "/var/lib/nginx"
            - name: "var-run"
              mountPath: "/var/run"
          ports:
            {{- range $key, $value := .Values.managementUi.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $value.containerPort }}
              protocol: {{ $value.protocol }}
            {{- end }}
          {{- if .Values.managementUi.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.managementUi.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.managementUi.probes.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.managementUi.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.managementUi.probes.liveness.failureThreshold }}
            successThreshold: {{ .Values.managementUi.probes.liveness.successThreshold }}
          {{- end }}
          {{- if .Values.managementUi.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.managementUi.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.managementUi.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.managementUi.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.managementUi.probes.readiness.failureThreshold }}
            successThreshold: {{ .Values.managementUi.probes.readiness.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.managementUi.resources | nindent 12 }}
      volumes:
        {{- if .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
        - name: "app-config"
          emptyDir: { }
          # NOTE: Workaround for removing the content of the entrypoint
        - name: "var-lib"
          emptyDir: { }
        - name: "var-run"
          emptyDir: { }
        - name: "nginx-conf"
          configMap:
            name: {{ printf "%s-nginx-conf" (include "common.names.fullname" .) }}

...

