# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH


---

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ printf "%s-open-policy-agent" (include "common.names.fullname" .) }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
spec:
  replicas: {{ .Values.openPolicyAgent.replicaCount }}
  selector:
    matchLabels:
      {{- $commonLabels := include "common.labels.matchLabels" . | fromYaml }}
      {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-open-policy-agent" (include "common.names.fullname" .)) }}
      {{- merge $uiLabels $commonLabels | toYaml | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-open-policy-agent.yaml") . | sha256sum }}
        {{- with .Values.openPolicyAgent.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
        {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-open-policy-agent" (include "common.names.fullname" .)) }}
        {{- $mergedLabels := merge $uiLabels $commonLabels }}
        {{- toYaml $mergedLabels | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.fullname" . }}
      {{- end }}
      {{- with .Values.openPolicyAgent.affinity }}
      affinity:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.openPolicyAgent.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.openPolicyAgent.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- if .Values.openPolicyAgent.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.openPolicyAgent.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if or .Values.imagePullSecrets .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
        {{- range .Values.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}
      containers:
        - name: "open-policy-agent"
          {{- if .Values.openPolicyAgent.containerSecurityContext.enabled }}
          securityContext:
            {{- omit .Values.openPolicyAgent.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ coalesce .Values.openPolicyAgent.image.registry .Values.global.imageRegistry }}/{{ .Values.openPolicyAgent.image.repository }}{{ if .Values.openPolicyAgent.image.sha256 }}@sha256:{{ .Values.openPolicyAgent.image.sha256 }}{{ else }}:{{ .Values.openPolicyAgent.image.tag }}{{ end }}"
          imagePullPolicy: {{ coalesce .Values.openPolicyAgent.image.pullPolicy .Values.global.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-open-policy-agent" (include "common.names.fullname" .) }}
          {{- with .Values.openPolicyAgent.extraEnvVars }}
          env:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          ports:
            {{- range $key, $value := .Values.openPolicyAgent.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $value.containerPort }}
              protocol: {{ $value.protocol }}
            {{- end }}
          {{- if .Values.openPolicyAgent.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.openPolicyAgent.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.openPolicyAgent.probes.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.openPolicyAgent.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.openPolicyAgent.probes.liveness.failureThreshold }}
            successThreshold: {{ .Values.openPolicyAgent.probes.liveness.successThreshold }}
          {{- end }}
          {{- if .Values.openPolicyAgent.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.openPolicyAgent.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.openPolicyAgent.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.openPolicyAgent.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.openPolicyAgent.probes.readiness.failureThreshold }}
            successThreshold: {{ .Values.openPolicyAgent.probes.readiness.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.openPolicyAgent.resources | nindent 12 }}

...
