# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH


---

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ printf "%s-authorization-api" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
spec:
  replicas: {{ .Values.authorizationApi.replicaCount }}
  selector:
    matchLabels:
      {{- $commonLabels := include "common.labels.matchLabels" . | fromYaml }}
      {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-authorization-api" (include "common.names.fullname" .)) }}
      {{- merge $uiLabels $commonLabels | toYaml | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-authorization-api.yaml") . | sha256sum }}
        {{- with .Values.authorizationApi.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
        {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-authorization-api" (include "common.names.fullname" .)) }}
        {{- $mergedLabels := merge $uiLabels $commonLabels }}
        {{- toYaml $mergedLabels | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.fullname" . }}
      {{- end }}
      {{- with .Values.authorizationApi.affinity }}
      affinity:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.authorizationApi.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.authorizationApi.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      {{- if .Values.authorizationApi.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.authorizationApi.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if or .Values.imagePullSecrets .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
        {{- range .Values.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}
      containers:
        - name: "authorization-api"
          {{- if .Values.authorizationApi.containerSecurityContext.enabled }}
          securityContext:
            {{- omit .Values.authorizationApi.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ coalesce .Values.authorizationApi.image.registry .Values.global.imageRegistry }}/{{ .Values.authorizationApi.image.repository }}{{ if .Values.authorizationApi.image.sha256 }}@sha256:{{ .Values.authorizationApi.image.sha256 }}{{ else }}:{{ .Values.authorizationApi.image.tag }}{{ end }}"
          imagePullPolicy: {{ coalesce .Values.authorizationApi.image.pullPolicy .Values.global.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-authorization-api" (include "common.names.fullname" .) }}
          {{- if .Values.authorizationApi.credentialSecretName }}
            - secretRef:
                name: {{ .Values.authorizationApi.credentialSecretName | quote }}
          {{- end }}
          {{- with .Values.authorizationApi.extraEnvVars }}
          env:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          ports:
            {{- range $key, $value := .Values.authorizationApi.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $value.containerPort }}
              protocol: {{ $value.protocol }}
            {{- end }}
          {{- if .Values.authorizationApi.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /guardian/authorization/openapi.json
              port: http
            initialDelaySeconds: {{ .Values.authorizationApi.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.authorizationApi.probes.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.authorizationApi.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.authorizationApi.probes.liveness.failureThreshold }}
            successThreshold: {{ .Values.authorizationApi.probes.liveness.successThreshold }}
          {{- end }}
          {{- if .Values.authorizationApi.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /guardian/authorization/openapi.json
              port: http
            initialDelaySeconds: {{ .Values.authorizationApi.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.authorizationApi.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.authorizationApi.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.authorizationApi.probes.readiness.failureThreshold }}
            successThreshold: {{ .Values.authorizationApi.probes.readiness.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.authorizationApi.resources | nindent 12 }}
          volumeMounts:
            - name: "secrets"
              mountPath: "/var/secrets"
            - name: "udm-adapter-user"
              mountPath: "/var/guardian"
            - name: "tmp"
              mountPath: "/tmp"
            {{- if .Values.authorizationApi.extraVolumeMounts }}
              {{- include "common.tplvalues.render" (dict "value" .Values.authorizationApi.extraVolumeMounts "context" .) | nindent 12 }}
            {{- end }}
      volumes:
        - name: "tmp"
          emptyDir: {}
        - name: "udm-adapter-user"
          configMap:
            name: {{ printf "%s-udm-adapter-user" (include "common.names.fullname" .) }}
        - name: "secrets"
          secret:
            secretName: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.authorizationApi.udm.auth.existingSecret "defaultNameSuffix" "udm-secret" "context" .) }}
            items:
              - key: {{ include "nubus-common.secrets.key" (dict "existingSecret" .Values.authorizationApi.udm.auth.existingSecret "key" "password" "context" .) }}
                path: udm-data-adapter-password
        {{- if .Values.authorizationApi.extraVolumes }}
          {{- include "common.tplvalues.render" (dict "value" .Values.authorizationApi.extraVolumes  "context" .) | nindent 8 }}
        {{- end }}
...
