# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

{{- if .Values.provisioning.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-provisioning" (include "common.names.fullname" .) }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.provisioning.extraLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.provisioning.extraLabels "context" . ) | nindent 4 }}
    {{- end }}
spec:
  ttlSecondsAfterFinished: {{ .Values.provisioning.ttlSecondsAfterFinished }}
  template:
    metadata:
      name: {{ printf "%s-provisioning" (include "common.names.fullname" .) }}
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/configmap-provisioning.yaml") . | sha256sum }}'
        {{- if .Values.provisioning.extraAnnotations }}
        {{ toYaml .Values.provisioning.extraAnnotations | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: {{ coalesce .Values.provisioning.restartPolicy .Values.global.restartPolicy | quote }}
      {{- with .Values.provisioning.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.provisioning.podSecurityContext }}
      securityContext:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
      initContainers:
      - name: "wait-for-keycloak-container"
        image: "{{ coalesce .Values.provisioning.image.registry .Values.global.imageRegistry }}/{{ .Values.provisioning.image.repository }}{{ if .Values.provisioning.image.sha256 }}@sha256:{{ .Values.provisioning.image.sha256 }}{{ else }}:{{ .Values.provisioning.image.tag }}{{ end }}"
        imagePullPolicy: {{ coalesce .Values.provisioning.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
        envFrom:
          - configMapRef:
              name: {{ printf "%s-provisioning-init" (include "common.names.fullname" .) }}
        {{- with .Values.provisioning.extraEnvVars }}
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        command: ["/usr/bin/python3", "/scripts/wait-for-keycloak.py"]
        {{- if .Values.provisioning.args }}
        args: {{ .Values.provisioning.args }}
        {{- end }}
        {{- with .Values.provisioning.resources }}
        resources:
        {{ toYaml . | indent 10 }}
        {{- end }}
        volumeMounts:
          - name: "wait-for-keycloak"
            mountPath: "/scripts"
          {{- if .Values.provisioning.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.provisioning.extraVolumeMounts "context" .) | nindent 10 }}
          {{- end }}
      containers:
      - name: "keycloak-provisioning"
        securityContext:
          {{- toYaml .Values.provisioning.securityContext | nindent 10 }}
        image: "{{ coalesce .Values.provisioning.provisioningImage.registry .Values.global.imageRegistry }}/{{ .Values.provisioning.provisioningImage.repository }}{{ if .Values.provisioning.provisioningImage.sha256 }}@sha256:{{ .Values.provisioning.provisioningImage.sha256 }}{{ else }}:{{ .Values.provisioning.provisioningImage.tag }}{{ end }}"
        imagePullPolicy: {{ coalesce .Values.provisioning.provisioningImage.imagePullPolicy .Values.global.imagePullPolicy | quote }}
        command:
          - /bin/bash
          - -c
          - |
            univention-keycloak \
            --keycloak-url $KEYCLOAK_URL \
            --realm $KEYCLOAK_REALM \
            --binduser $KEYCLOAK_USERNAME \
            --bindpwdfile /credentials/keycloak.secret \
            oidc/rp create \
            guardian-ui \
            --app-url $KEYCLOAK_APP_BASE_URL \
            --redirect-uri $KEYCLOAK_APP_BASE_URL/univention/guardian/* \
            --add-guardian-audience-mapper \
            --add-dn-mapper \
            --add-audience-mapper \
            --audience-to-map guardian \
            --admin-url $KEYCLOAK_APP_BASE_URL \
            --pkce-code-challenge-method "" \
            --host-fqdn $KEYCLOAK_HOST \
            --public-client \
            --default-scopes "basic" \
            --web-origins $KEYCLOAK_APP_BASE_URL \
            && \
            univention-keycloak \
            --keycloak-url $KEYCLOAK_URL \
            --realm $KEYCLOAK_REALM \
            --binduser $KEYCLOAK_USERNAME \
            --bindpwdfile /credentials/keycloak.secret \
            oidc/rp create \
            guardian-management-api \
            --service-accounts-enabled \
            --client-secret $GUARDIAN_MANAGEMENT_API_CLIENT_SECRET \
            --app-url $KEYCLOAK_APP_BASE_URL \
            --redirect-uri $KEYCLOAK_APP_BASE_URL/guardian/* \
            --add-guardian-management-mappers \
            --admin-url $KEYCLOAK_APP_BASE_URL \
            --pkce-code-challenge-method "" \
            --host-fqdn $KEYCLOAK_HOST \
            --web-origins $KEYCLOAK_APP_BASE_URL \
            && \
            univention-keycloak \
            --keycloak-url $KEYCLOAK_URL \
            --realm $KEYCLOAK_REALM \
            --binduser $KEYCLOAK_USERNAME \
            --bindpwdfile /credentials/keycloak.secret \
            oidc/rp create \
            guardian-scripts \
            --direct-access-grants \
            --app-url $KEYCLOAK_APP_BASE_URL \
            --redirect-uri $KEYCLOAK_APP_BASE_URL/guardian/* \
            --redirect-uri $KEYCLOAK_APP_BASE_URL/univention/guardian/* \
            --add-guardian-audience-mapper \
            --add-dn-mapper \
            --add-audience-mapper \
            --audience-to-map guardian-scripts \
            --admin-url $KEYCLOAK_APP_BASE_URL \
            --pkce-code-challenge-method "" \
            --host-fqdn $KEYCLOAK_HOST \
            --public-client \
            --web-origins $KEYCLOAK_APP_BASE_URL
        envFrom:
          - configMapRef:
              name: {{ printf "%s-provisioning-env" (include "common.names.fullname" .) }}
        env:
          - name: KEYCLOAK_PASSWORD
            {{- include "guardian.provisioning.config.keycloak.password" . | nindent 12 }}
          - name: GUARDIAN_MANAGEMENT_API_CLIENT_SECRET
            {{- include "guardian.provisioning.config.managementApi.clientSecret" . | nindent 12 }}
        {{- with .Values.provisioning.extraEnvVars }}
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.provisioning.args }}
        args: {{ .Values.provisioning.args }}
        {{- end }}
        {{- with .Values.provisioning.resources }}
        resources:
        {{ toYaml . | indent 10 }}
        {{- end }}
        volumeMounts:
          - mountPath: "/credentials/keycloak.secret"
            name: "keycloak-credentials-volume"
            subPath: {{ .Values.provisioning.config.keycloak.credentialSecret.key | quote }}
          - name: "temp-dir"
            mountPath: "/tmp"
          {{- if .Values.provisioning.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.provisioning.extraVolumeMounts "context" .) | nindent 10 }}
          {{- end }}
      {{- with .Values.provisioning.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.provisioning.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.provisioning.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
        - name: "wait-for-keycloak"
          configMap:
            name: {{ printf "%s-provisioning-init" (include "common.names.fullname" .) }}
        - name: "keycloak-credentials-volume"
          secret:
            secretName: {{ (include "guardian.provisioning.config.keycloak.credentialSecret.name" . ) | quote }}
        - name: "temp-dir"
          emptyDir:
            sizeLimit: "20Mi"
        {{- if .Values.provisioning.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.provisioning.extraVolumes  "context" .) | nindent 8 }}
        {{- end }}
  backoffLimit: {{ .Values.provisioning.backoffLimit }}
...
{{- end }}
