# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

{{- if .Values.provisioning.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "common.names.fullname" . }}-provisioning-{{ .Release.Revision }}"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
spec:
  ttlSecondsAfterFinished: {{ .Values.provisioning.ttlSecondsAfterFinished }}
  template:
    metadata:
      name: "{{ include "common.names.fullname" . }}-provisioning-{{ .Release.Revision }}"
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/configmap-provisioning.yaml") . | sha256sum }}'
        {{- if .Values.provisioning.extraAnnotations }}
        {{ toYaml .Values.provisioning.extraAnnotations | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: {{ coalesce .Values.provisioning.restartPolicy .Values.global.restartPolicy | quote }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.fullname" . }}
      {{- end }}
      {{- if or .Values.imagePullSecrets .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
        {{- range .Values.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}
      {{- if .Values.provisioning.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.provisioning.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
      - name: "wait-for-keycloak-container"
        image: "{{ coalesce .Values.provisioning.image.registry .Values.global.imageRegistry }}/{{ .Values.provisioning.image.repository }}{{ if .Values.provisioning.image.sha256 }}@sha256:{{ .Values.provisioning.image.sha256 }}{{ else }}:{{ .Values.provisioning.image.tag }}{{ end }}"
        imagePullPolicy: {{ coalesce .Values.provisioning.image.pullPolicy .Values.global.imagePullPolicy | quote }}
        {{- if .Values.provisioning.containerSecurityContext.enabled }}
        securityContext:
          {{- omit .Values.provisioning.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ printf "%s-provisioning-init" (include "common.names.fullname" .) }}
        {{- with .Values.provisioning.extraEnvVars }}
        env:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        command: ["wait-for-keycloak.py"]
        {{- if .Values.provisioning.args }}
        args: {{ .Values.provisioning.args }}
        {{- end }}
        {{- with .Values.provisioning.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
          {{- if .Values.provisioning.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.provisioning.extraVolumeMounts "context" .) | nindent 10 }}
          {{- end }}
      containers:
      - name: "main"
        {{- if .Values.provisioning.containerSecurityContext.enabled }}
        securityContext:
          {{- omit .Values.provisioning.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        image: "{{ coalesce .Values.provisioning.provisioningImage.registry .Values.global.imageRegistry }}/{{ .Values.provisioning.provisioningImage.repository }}{{ if .Values.provisioning.provisioningImage.sha256 }}@sha256:{{ .Values.provisioning.provisioningImage.sha256 }}{{ else }}:{{ .Values.provisioning.provisioningImage.tag }}{{ end }}"
        imagePullPolicy: {{ coalesce .Values.provisioning.provisioningImage.pullPolicy .Values.global.imagePullPolicy | quote }}
        command:
          - /bin/bash
          - -c
          - |
            univention-keycloak \
            --keycloak-url $KEYCLOAK_URL \
            --realm $KEYCLOAK_REALM \
            --binduser $KEYCLOAK_USERNAME \
            --bindpwdfile /credentials/keycloak.secret \
            oidc/rp create \
            guardian-ui \
            --app-url $KEYCLOAK_APP_BASE_URL \
            --redirect-uri $KEYCLOAK_APP_BASE_URL/guardian/* \
            --redirect-uri $KEYCLOAK_APP_BASE_URL/univention/guardian/* \
            --add-guardian-audience-mapper \
            --add-dn-mapper \
            --add-audience-mapper \
            --audience-to-map guardian \
            --admin-url $KEYCLOAK_APP_BASE_URL \
            --pkce-code-challenge-method "" \
            --host-fqdn $KEYCLOAK_HOST \
            --public-client \
            --default-scopes "basic" \
            --web-origins $KEYCLOAK_APP_BASE_URL \
            && \
            univention-keycloak \
            --keycloak-url $KEYCLOAK_URL \
            --realm $KEYCLOAK_REALM \
            --binduser $KEYCLOAK_USERNAME \
            --bindpwdfile /credentials/keycloak.secret \
            oidc/rp create \
            guardian-management-api \
            --service-accounts-enabled \
            --client-secret $GUARDIAN_MANAGEMENT_API_CLIENT_SECRET \
            --app-url $KEYCLOAK_APP_BASE_URL \
            --redirect-uri $KEYCLOAK_APP_BASE_URL/guardian/* \
            --add-guardian-management-mappers \
            --admin-url $KEYCLOAK_APP_BASE_URL \
            --pkce-code-challenge-method "" \
            --host-fqdn $KEYCLOAK_HOST \
            --web-origins $KEYCLOAK_APP_BASE_URL \
            && \
            univention-keycloak \
            --keycloak-url $KEYCLOAK_URL \
            --realm $KEYCLOAK_REALM \
            --binduser $KEYCLOAK_USERNAME \
            --bindpwdfile /credentials/keycloak.secret \
            oidc/rp create \
            guardian-scripts \
            --direct-access-grants \
            --app-url $KEYCLOAK_APP_BASE_URL \
            --redirect-uri $KEYCLOAK_APP_BASE_URL/guardian/* \
            --redirect-uri $KEYCLOAK_APP_BASE_URL/univention/guardian/* \
            --add-guardian-audience-mapper \
            --add-dn-mapper \
            --add-audience-mapper \
            --audience-to-map guardian-scripts \
            --admin-url $KEYCLOAK_APP_BASE_URL \
            --pkce-code-challenge-method "" \
            --host-fqdn $KEYCLOAK_HOST \
            --default-scopes "basic" \
            --public-client \
            --web-origins $KEYCLOAK_APP_BASE_URL
        envFrom:
          - configMapRef:
              name: {{ printf "%s-provisioning-env" (include "common.names.fullname" .) }}
        env:
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.provisioning.keycloak.auth.existingSecret "defaultNameSuffix" "keycloak-credentials" "context" .) }}
                key: {{ include "nubus-common.secrets.key" (dict "existingSecret" .Values.provisioning.keycloak.auth.existingSecret "key" "adminPassword" "context" .) }}
          - name: GUARDIAN_MANAGEMENT_API_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.managementApi.oauth.auth.existingSecret "defaultNameSuffix" "keycloak-client-secret" "context" .) }}
                key: {{ include "nubus-common.secrets.key" (dict "existingSecret" .Values.managementApi.oauth.auth.existingSecret "key" "clientSecret" "context" .) }}
        {{- with .Values.provisioning.extraEnvVars }}
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.provisioning.args }}
        args: {{ .Values.provisioning.args }}
        {{- end }}
        {{- with .Values.provisioning.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
          - mountPath: "/credentials/keycloak.secret"
            name: "keycloak-credentials-volume"
            subPath: {{ include "nubus-common.secrets.key" (dict "existingSecret" .Values.provisioning.keycloak.auth.existingSecret "key" "adminPassword" "context" .) }}
          - name: "temp-dir"
            mountPath: "/tmp"
          {{- if .Values.provisioning.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.provisioning.extraVolumeMounts "context" .) | nindent 10 }}
          {{- end }}
      {{- with .Values.provisioning.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.provisioning.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.provisioning.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: "keycloak-credentials-volume"
          secret:
            secretName: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.provisioning.keycloak.auth.existingSecret "defaultNameSuffix" "keycloak-credentials" "context" .) }}
        - name: "temp-dir"
          emptyDir:
            sizeLimit: "20Mi"
        {{- if .Values.provisioning.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.provisioning.extraVolumes  "context" .) | nindent 8 }}
        {{- end }}
  backoffLimit: {{ .Values.provisioning.backoffLimit }}
...
{{- end }}
