{{/*
SPDX-FileCopyrightText: 2023 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}
{{ if .Values.provisioning.keycloak.auth.password }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "keycloak-credentials" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- if .Values.additionalAnnotations }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
    {{- end }}
stringData:
  password: {{ .Values.provisioning.keycloak.auth.password | quote }}
...
{{ end }}
