# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-authorization-api" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.authorizationApi.extraLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.authorizationApi.extraLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.authorizationApi.extraAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.authorizationApi.extraAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  udmDataAdapterUsername: {{ .Values.authorizationApi.config.udmDataAdapterUsername | b64enc | quote }}
  udmDataAdapterPassword: {{ .Values.authorizationApi.config.udmDataAdapterPassword | b64enc | quote }}
...

