---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-management-api" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.managementApi.extraLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.managementApi.extraLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.managementApi.extraAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.managementApi.extraAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  oauthAdapterM2mSecret: {{ .Values.managementApi.config.oauthAdapterM2mSecret | b64enc | quote }}
...

