# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---

imagePullSecrets:
  - "kyverno-test"

global:
  imageRegistry: "my_private_registry.domain.tld"
  imagePullSecrets:
    - "kyverno-test"
  imagePullPolicy: "kyverno"

authorizationApi:
  replicaCount: 42
managementApi:
  replicaCount: 42
managementUi:
  replicaCount: 42
openPolicyAgent:
  replicaCount: 42

...
